name: Run Tests NodeJS

on: [push, fork, workflow_dispatch]

jobs:
  run_tests:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js@16
        uses: actions/setup-node@v3
        with:
          node-version: '12'

